### PR TITLE
setting more the one tag at once

### PR DESCRIPTION
**Pull request by hmueller01**
I added a new method (setTags()) to set more than one tag per subprocess call.
If you like it please add it to your repository. Thanks.

### CODE REVIEW

**Comment by EdLeafe** [comment]
This is a great addition. I'm just wondering whether it would be better to pass a dict of the desired keys and values rather than two separate lists. What do you think?

**Comment by hmueller01** [comment]
A dict is a good idea. Solves the issue that both lists have different length and a possible shift of tag and value. No matter what, both is fine for me. Or do you like me to make a new suggestion?

**Comment by EdLeafe** [comment]
Thanks!

**Comment by hmueller01** [comment]
Thanks for adding my suggestions.

**Pull request merged**
